import fs from 'node:fs'
import path from 'node:path'
import esbuild from 'esbuild'

const ROOT_DIR = process.cwd()
const UI_DIST_PATH = path.join(ROOT_DIR, 'dist-ui', 'index.html')
const EMBEDDED_UI_TS = path.join(ROOT_DIR, 'src', 'agent', 'embedded-ui.ts')
const AGENT_ENTRY = path.join(ROOT_DIR, 'src', 'agent', 'index.ts')
const OUT_FILE = path.join(ROOT_DIR, 'dist', 'burned-agent.js')

async function buildAgent() {
  console.log('\n📦 [1/3] Reading compiled Vue UI from dist-ui/index.html...')
  if (!fs.existsSync(UI_DIST_PATH)) {
    throw new Error(`UI build not found at ${UI_DIST_PATH}. Run "npm run build:ui" first.`)
  }

  const uiHtml = fs.readFileSync(UI_DIST_PATH, 'utf-8')
  console.log(`       Embedded UI size: ${(Buffer.byteLength(uiHtml) / 1024).toFixed(1)} KB`)

  console.log('📦 [2/3] Embedding UI HTML into agent source...')
  const embeddedCode = `// Auto-generated by build.agent.js\nexport const EMBEDDED_HTML = ${JSON.stringify(uiHtml)};\n`
  fs.writeFileSync(EMBEDDED_UI_TS, embeddedCode, 'utf-8')

  console.log('📦 [3/3] Bundling with esbuild into single dist/burned-agent.js...')
  if (!fs.existsSync(path.join(ROOT_DIR, 'dist'))) {
    fs.mkdirSync(path.join(ROOT_DIR, 'dist'), { recursive: true })
  }

  await esbuild.build({
    entryPoints: [AGENT_ENTRY],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    outfile: OUT_FILE,
    minify: true,
    sourcemap: false
  })

  const stats = fs.statSync(OUT_FILE)
  const sizeMb = (stats.size / 1024 / 1024).toFixed(2)
  console.log(`\n🎉 SUCCESS! Generated single-file agent:`)
  console.log(`   File: dist/burned-agent.js (${sizeMb} MB - includes entire Vue UI, Logo, & Backend)`)
  console.log(`   Usage on any VDS:`)
  console.log(`     node dist/burned-agent.js`)
  console.log(`     pm2 start dist/burned-agent.js --name burned-agent\n`)
}

buildAgent().catch(err => {
  console.error('❌ Build failed:', err)
  process.exit(1)
})
